source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JTAppleCalendar_Example' do
  pod 'JTAppleCalendar', :path => '../'
end

target 'JTAppleCalendar_Tests' do
  pod 'JTAppleCalendar', :path => '../'

  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end
